on: [push]

name: Rust Build

jobs:
  rust:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.3.4
      
  substrate:
    runs-on: ubuntu-latest
    needs: rust
    steps:
    - name: Install Substrate
      run: |
        curl https://getsubstrate.io -sSf | bash -s -- --fast
        source ~/.cargo/env
        rustup component add rust-src --toolchain nightly
        rustup target add wasm32-unknown-unknown --toolchain stable
        rustup install nightly-2020-10-06
        rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06
    - name: Install canvas-node
      run: |
        cargo +nightly-2020-10-06 install canvas-node --git https://github.com/paritytech/canvas-node.git --tag v0.1.0 --force
    - name: Install cargo-contract 
      run: |
        cargo install cargo-contract --git https://github.com/paritytech/cargo-contract.git --tag v0.7.0 --force
        cargo contract --help
    - name: Install flipper 
      run: |
        cargo contract new flipper
        cd flipper/
    - name: Test flipper 
      run: cargo +nightly test
    - name: Build contract
      run: |
        cargo +nightly contract build
        cargo +nightly contract generate-metadata
      shell: bash
