on: [push]

name: Rust Build

jobs:
  rust:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.3.4
  check:
    runs-on: ubuntu-latest
    needs: rust
    steps:
    - name: check env
      run: |
        curl https://getsubstrate.io -sSf | bash -s -- --fast
      shell: bash
