on: [push]

name: Rust Build

jobs:
  rust:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.3.4
      
  substrate:
    runs-on: ubuntu-latest
    needs: rust
    steps:
    - name: Install Substrate
      run: |
        curl https://getsubstrate.io -sSf | bash -s -- --fast
        source ~/.cargo/env
        rustup target add wasm32-unknown-unknown --toolchain stable
        rustup component add rust-src --toolchain nightly
        cargo install canvas-node --git https://github.com/paritytech/canvas-node.git --force
        cargo install cargo-contract --git https://github.com/paritytech/cargo-contract.git --branch v0.7.0-rc1 --force
        cargo contract --help
      shell: bash
