on: [push]

name: Rust Build

jobs:
  rust:
    name: Install Rust
    runs-on: macos-10.14
    steps:
    - name: Set up a Rust toolchain
      run: |
        curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh
        brew update
        brew install openssl cmake llvm
        curl https://sh.rustup.rs -sSf | sh
        source ~/.cargo/env
        rustup default stable
        rustup install nightly-2020-10-06-x86_64-apple-darwin
        rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06-x86_64-apple-darwin
      shell: bash
     
  substrate:
    runs-on: macos-10.14
    needs: rust
    steps:
    - name: Install Node
      run: |
        source ~/.cargo/env
    - name: Install canvas-node
      run: |
        cargo +nightly-2020-10-06 install canvas-node --git https://github.com/paritytech/canvas-node.git --tag v0.1.0 --force
    - name: Install cargo-contract 
      run: |
        rustup component add rust-src
        cargo install cargo-contract --git https://github.com/paritytech/cargo-contract.git --tag v0.7.0 --force
        cargo contract --help
        rustup show
    - name: Install flipper 
      run: |
        cargo contract new flipper
        cd flipper/
        pwd
    - name: Test flipper 
      run: |
        rustup install nightly-2020-06-01
        cargo +nightly-2020-06-01 test
    - name: Build contract
      run: |
        cargo +nightly contract build
        cargo +nightly contract generate-metadata
      shell: bash
