name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: lsb_release -a

  rust:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v2
    - name: rustup show
    - run: rustup show
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
